name: Python CI/CD Workflow

on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Run tests
      run: |
        python3 hello_world.py

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: |
        echo "Finalizado"